/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projett;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Fabrice
 */
public class AjterEcl extends javax.swing.JFrame {

    /**
     * Creates new form AjterEcl
     */
    public AjterEcl() {
        initComponents();
    }
        //Déclaration des tableaux qui contiendront les données récupérées dans le fihier excel
        ArrayList<String> entetesList = new ArrayList<>();
        ArrayList<String> nomsList = new ArrayList<>();
        ArrayList<String> postNomsList = new ArrayList<>();
        ArrayList<String> prenomList = new ArrayList<>();
        ArrayList<String> sexeList = new ArrayList<>();
        ArrayList<Integer> agesList = new ArrayList<>();
        ArrayList<Integer> classeList = new ArrayList<>();
        ArrayList<Integer> codeEcoleList = new ArrayList<>();
        ArrayList<Integer> numPermanantList = new ArrayList<>();
        
        //Model du tablea d'affichage des informations lorsqu'on choisi le fichier
        
        String element[] = {"Nom", "Post-Nom", "Prenom", "Sexe", "age", "Classe", "Numero permanant"};
        String[] ligne = new String[7];
        DefaultTableModel model = new DefaultTableModel(null, element);
        
        
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        choiseFileBtn = new javax.swing.JButton();
        nomEcole = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codeRegion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        codeEcole = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        afficheSchoolDataTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        nombreEleves = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ajouter les données globales d'une école");

        choiseFileBtn.setText("Choisir le fichier excel ");
        choiseFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiseFileBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Données des élèves");

        jLabel3.setText("Nom de l'école ");

        jLabel4.setText("Code de l'écode");

        jLabel5.setText("Code de la région");

        afficheSchoolDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Post -Nom", "Prenom", "Sexe", "age", "Classe", "Numero permanant"
            }
        ));
        jScrollPane1.setViewportView(afficheSchoolDataTable);

        jLabel6.setText("Nombre d'élèves");

        nombreEleves.setText("0");

        addBtn.setText("Ajouter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(nomEcole, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeEcole, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(choiseFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreEleves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomEcole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeEcole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreEleves))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiseFileBtn)
                    .addComponent(addBtn))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choiseFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiseFileBtnActionPerformed
        
       
        
         
        //ouveture du fichier
        JFileChooser openFileChooser = new JFileChooser();
        openFileChooser.setDialogTitle("Choisir le ficheir");
        openFileChooser.removeChoosableFileFilter(openFileChooser.getFileFilter());
        FileFilter filter = new FileNameExtensionFilter("Excel File(.xlsx)", "xlsx");
        openFileChooser.setFileFilter(filter);
        
          if(openFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            File inputFile = openFileChooser.getSelectedFile();
            try (FileInputStream in = new FileInputStream(inputFile)) {
                    XSSFWorkbook importedFile = new XSSFWorkbook(in);
                    XSSFSheet sheet1 = importedFile.getSheetAt(0); 
                    
                    Iterator<Row> rowIterator = sheet1.rowIterator();
                    while (rowIterator.hasNext()){
                        Row row = rowIterator.next();
                        Iterator<Cell> cellIterator = row.cellIterator();
                        while (cellIterator.hasNext()){
                            Cell cell = cellIterator.next();
                            if(row.getRowNum() == 0){
                                entetesList.add(cell.getStringCellValue());
                            } else {
                                if (cell.getColumnIndex() == 0) {
                                    nomsList.add(cell.getStringCellValue());
                                } else  if (cell.getColumnIndex() == 1 ){
                                    postNomsList.add(cell.getStringCellValue());
                                }else  if (cell.getColumnIndex() == 2 ){
                                    prenomList.add(cell.getStringCellValue());
                                }else  if (cell.getColumnIndex() == 3 ){
                                    sexeList.add(cell.getStringCellValue());
                                }else  if (cell.getColumnIndex() == 4 ){
                                    agesList.add((int)cell.getNumericCellValue());
                                }else  if (cell.getColumnIndex() == 5 ){
                                    classeList.add((int)cell.getNumericCellValue());
                                }else  if (cell.getColumnIndex() == 6 ){
                                    numPermanantList.add((int)cell.getNumericCellValue());
                                }
                            }
                        }
                        
                    }
                    in.close();
                    
                    
        
                    //Statement stm = connection.connectbd().createStatement();
                    //String requete = "SELECT * FROM  ecole ";
                    
                    
                    int max = nomsList.size(); 
                    for (int i = 0; i<max - 1; i++){
                        ligne[0] = nomsList.get(i); 
                        ligne[1] = postNomsList.get(i);
                        ligne[2] = prenomList.get(i);
                        ligne[3] = sexeList.get(i);
                        ligne[4] = agesList.get(i).toString();
                        ligne[5] = classeList.get(i).toString();
                        ligne[6] = numPermanantList.get(i).toString();
                        
                        model.addRow(ligne);
                        
                    }
                    afficheSchoolDataTable.setModel(model);
                    
                    
                     
                    
            } catch (Exception e) {
                Logger.getLogger(AjterEcl.class.getName()).log(Level.SEVERE, null, e);
            }
            
        }
    }//GEN-LAST:event_choiseFileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjterEcl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjterEcl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjterEcl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjterEcl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjterEcl().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable afficheSchoolDataTable;
    private javax.swing.JButton choiseFileBtn;
    private javax.swing.JTextField codeEcole;
    private javax.swing.JTextField codeRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomEcole;
    private javax.swing.JLabel nombreEleves;
    // End of variables declaration//GEN-END:variables
}
